### PR TITLE
Project structure and dependencies

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. Thx.

**Comment by stulees** [comment]
@donnapep I see some differences between this webpack config file and the one I created when following the tutorial I did, here's what it looked like:

```
var HTMLWebPackPlugin = require("html-webpack-plugin");
var HTMLWebPackPluginConfig = new HTMLWebPackPlugin({
  template: __dirname + "/app/index.html",
  filename: "index.html",
  inject: "body"
});

module.exports = {
  entry: [
    "./app/index.js"
  ],
  output: {
    path: __dirname + "/dist",
    filename: "index_bundle.js"
  },
  module: {
    loaders: [
      {test: /\.js$/, exclude: /node_modules/, loader: "babel-loader"}
    ]
  },
  plugins: [HTMLWebPackPluginConfig]
```

Here were the node dependencies:

```
"dependencies": {
    "axios": "^0.10.0",
    "react": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-router": "^2.3.0"
  },
  "devDependencies": {
    "babel-core": "^6.7.6",
    "babel-loader": "^6.2.4",
    "babel-preset-react": "^6.5.0",
    "html-webpack-plugin": "^2.16.0",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1"
  }
```

and it also had a `.babelrc` config file containing:

```
{
  "presets": [
    "react"
  ]
}
```

If you'd like to just move forward with what you have for now I'm fine with that.

**Comment by donnapep** [comment]
@stulees So I think HTMLWebPackagePlugin generates an `index.html` file automatically. Since I've already created one, I'm not going to include that, but it might be useful in future.

I think otherwise both versions are mostly equivalent. The one in this PR gets things like version number and entry point from `package.json`, while the other version is specified directly in `webpack.config.js`. It will create a `react-spreadsheet-prototype.1.0.0.js' file and a corresponding source map in `dist` folder. Version number and file name come from `package.json`, as does the entry point. Not sure if I like attaching the version number or not though.

I don't know what `axios` is, but I haven't seen it before so I'm inclined to leave it off unless needed. Same goes for `webpack-dev-server`. I think using your own local web server may be good enough, although that server may be needed for watching. And we won't need `react-router`.

**Comment by stulees** [comment]
@donnapep All sounds fine 👍 

HTMLWebPackagePlugin basically inserts a `<script>` tag pointing to your compiled dist/ JS and generates an index.html file. It's a convenient plugin, somewhat along the lines of `gulp-usemin` that we use in our builds. 

`axios` is for making AJAX requests with promises, it's the React equivalent of `$http` in Angular. At least that's how it was used in the tutorial.

**Comment by donnapep** [comment]
@stulees OK, we can refine in Spreadsheet Widget once we have a better idea of what we like / don't like. Thx.

**Pull request merged**
