### PR TITLE
Header, body, row, and custom column styling

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees code looks good. could I see how it looks? cheers

**Comment by stulees** [comment]
@rodrigopavezi http://goo.gl/czejHA

**Comment by rodrigopavezi** [comment]
@stulees cool 👍 cheers

**Pull request merged**
