### PR TITLE
Add support for scrolling

### PR DESCRIPTION
**Pull request by donnapep**
Add `responsive-fixed-data-table` dependency in order to support scrolling.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by stulees** [comment]
@donnapep Looks good 👍

**Comment by stulees** [comment]
@donnapep @rodrigopavezi Please review latest commit, thanks. You can view demo here - http://goo.gl/vmN9jO

**Comment by rodrigopavezi** [comment]
@stulees looks good 👍 cheers

**Pull request merged**
